# Generated by Django 5.2.7 on 2025-10-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardiologista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('crm', models.CharField(blank=True, max_length=50, null=True)),
                ('uf', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=255, null=True)),
                ('especialidade', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fid', models.CharField(blank=True, max_length=255, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('foto', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cardiologista',
                'verbose_name_plural': 'Cardiologistas',
                'db_table': 'cardiologista',
                'ordering': ['valor', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroundfoto', models.BinaryField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('feedback', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
                'db_table': 'config',
            },
        ),
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('crm', models.CharField(max_length=50)),
                ('situacao', models.CharField(blank=True, max_length=50, null=True)),
                ('uf', models.CharField(max_length=5)),
                ('cidade', models.CharField(max_length=100)),
                ('nome_fantasia', models.CharField(blank=True, max_length=150, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=30, null=True)),
                ('especialidade', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=150, null=True)),
                ('complemento', models.CharField(blank=True, max_length=150, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'db_table': 'medicos',
                'ordering': ['valor', 'nome'],
            },
        ),
    ]
