# Generated by Django 5.2.7 on 2025-11-18 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBO',
            fields=[
                ('cod_cbo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cod_cbo_label', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'verbose_name': 'CBO',
                'verbose_name_plural': 'CBOs',
                'ordering': ['cod_cbo'],
            },
        ),
        migrations.CreateModel(
            name='CBOEspecialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cbo_especialidades_label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Especialidade CBO',
                'verbose_name_plural': 'Especialidades CBO',
                'ordering': ['cod_cbo_especialidades_label'],
            },
        ),
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_razao_social', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('no_fantasia', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Clínica',
                'verbose_name_plural': 'Clínicas',
                'ordering': ['no_fantasia'],
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('nu_endereco', models.CharField(blank=True, max_length=50, null=True)),
                ('no_logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('no_bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('no_municipio', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('co_sigla_estado', models.CharField(blank=True, db_index=True, max_length=2, null=True)),
                ('co_cep', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['no_logradouro'],
            },
        ),
        migrations.AlterModelOptions(
            name='medicos',
            options={'ordering': ['no_profissional'], 'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.RenameField(
            model_name='medicos',
            old_name='situacao',
            new_name='co_conselho_classe',
        ),
        migrations.RemoveField(
            model_name='medicos',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='medicos',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='medicos',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='medicos',
            name='crm',
        ),
        migrations.RemoveField(
            model_name='medicos',
            name='especialidade',
        ),
        migrations.RemoveField(
            model_name='medicos',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='medicos',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='medicos',
            name='nome_fantasia',
        ),
        migrations.RemoveField(
            model_name='medicos',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='medicos',
            name='uf',
        ),
        migrations.RemoveField(
            model_name='medicos',
            name='valor',
        ),
        migrations.AddField(
            model_name='medicos',
            name='no_profissional',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicos',
            name='nu_registro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicos',
            name='nu_telefone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicos',
            name='sg_uf_crm',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='cardiologista',
            name='cidade',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cardiologista',
            name='especialidade',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cardiologista',
            name='nome',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cardiologista',
            name='uf',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cardiologista',
            name='valor',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='cardiologista',
            index=models.Index(fields=['nome'], name='idx_cardio_nome'),
        ),
        migrations.AddIndex(
            model_name='cardiologista',
            index=models.Index(fields=['cidade'], name='idx_cardio_cidade'),
        ),
        migrations.AddIndex(
            model_name='cardiologista',
            index=models.Index(fields=['uf'], name='idx_cardio_uf'),
        ),
        migrations.AddIndex(
            model_name='cardiologista',
            index=models.Index(fields=['especialidade'], name='idx_cardio_espec'),
        ),
        migrations.AddIndex(
            model_name='cbo',
            index=models.Index(fields=['cod_cbo_label'], name='idx_cbo_label'),
        ),
        migrations.AddField(
            model_name='medicos',
            name='cod_cbo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicos', to='api.cbo'),
        ),
        migrations.AddField(
            model_name='cboespecialidade',
            name='cbo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='api.cbo'),
        ),
        migrations.AddField(
            model_name='medicos',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicos', to='api.clinica'),
        ),
        migrations.AddIndex(
            model_name='medicos',
            index=models.Index(fields=['no_profissional'], name='idx_medicos_nome'),
        ),
        migrations.AddIndex(
            model_name='medicos',
            index=models.Index(fields=['cod_cbo'], name='idx_medicos_cbo'),
        ),
        migrations.AddIndex(
            model_name='medicos',
            index=models.Index(fields=['clinica'], name='idx_medicos_clinica'),
        ),
        migrations.AddIndex(
            model_name='endereco',
            index=models.Index(fields=['co_cep'], name='idx_endereco_cep'),
        ),
        migrations.AddIndex(
            model_name='endereco',
            index=models.Index(fields=['no_municipio'], name='idx_endereco_mun'),
        ),
        migrations.AddIndex(
            model_name='endereco',
            index=models.Index(fields=['co_sigla_estado'], name='idx_endereco_uf'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinicas', to='api.endereco'),
        ),
        migrations.AlterUniqueTogether(
            name='cboespecialidade',
            unique_together={('cbo', 'cod_cbo_especialidades_label')},
        ),
        migrations.AddIndex(
            model_name='clinica',
            index=models.Index(fields=['no_razao_social'], name='idx_clinica_razao'),
        ),
        migrations.AddIndex(
            model_name='clinica',
            index=models.Index(fields=['no_fantasia'], name='idx_clinica_fant'),
        ),
    ]
